<?php

use think\Controller;

/**
 * 登录
 * User: HanFL
 * Date: 2018/2/7
 * Time: 14:04
 */
class Login extends Controller
{
    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub
        if (session("admin_id")) {
            $this->redirect('index/index');
        }
    }

    private $cache_model, $system;

    public function index()
    {
        if (request()->post()) {
            $admin = new Admin();
            $data = input('post.');
            if ($this->check($data['captcha'])) {
                return json(array('code' => 0, 'msg' => '验证码错误'));
            }
            $result_code = $admin->login($data);
            if ($result_code == 1) {
                return json(array('code' => 1, 'msg' => '登录成功!', 'url' => url('index/index')));
            } else {
                return json(array('code' => 0, 'msg' => '用户名或密码错误，请重新输入!'));
            }
        } else {
            $this->cache_model = array('Module', 'Role', 'Category', 'Posid', 'Field', 'System');
            $this->system = F('System');
            if (empty($this->system)) {
                foreach ($this->cache_model as $r) {
                    savecache($r);
                }
            }
            return $this->fetch();
        }
    }

    public function check($code)
    {
        return captcha_check($code);
    }

}