<?php

use think\Controller;

/**
 * Created by PhpStorm.
 * User: HanFL
 * Date: 2018/2/7
 * Time: 14:04
 */

class Login extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (session("admin_id")){
            $this->redirect('index/index');
        }
    }

    public function index(){
        if (request()->post()){

        }else{

            return $this->fetch();
        }
    }

}